  cmake  -B build -S . -DCMAKE_BUILD_TYPE=release \
          -DGTSAM_BUILD_UNSTABLE=0 -DGTSAM_BUILD_CONVENIENCE_LIBRARIES=OFF \
          -DGTSAM_BUILD_PYTHON=0 -DGTSAM_INSTALL_MATLAB_TOOLBOX=1 \
          -DGTSAM_WITH_TBB=ON \
          -DGTSAM_WITH_EIGEN_MKL=OFF \
          -DGTSAM_TANGENT_PREINTEGRATION=false \
          -DGTSAM_POSE3_EXPMAP=true \
          -DGTSAM_ROT3_EXPMAP=true 
  #        -DCMAKE_VERBOSE_MAKEFILE=ON . |& tee CMAKE_OUTPUT_LOG.txt .. 
